version: '3.8'
services:
  backend:
    container_name: node-api
    build:  
      context: ./node
      dockerfile: Dockerfile.back
    volumes:
      - ./node/:/api
    ports:
      - "3030:3030"
    depends_on:
      - db

  frontend:
    build:
      context: ./sistema-financeiro # Ajuste para a pasta do seu projeto Next.js
      dockerfile: Dockerfile.front
    container_name: next_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./sistema-financeiro:/app
    depends_on:
      - backend
  
  db:
    image: postgres
    container_name: postgres-db
    environment:
      environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nomedomeubanco
    volumes:
      - teste_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432

volumes:
  teste_data:
